<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=gb18030">
  
  <title>CONEXION GPRS</title>
 </head>
 <body>
<?php
        $cadena="Te felicito porque has logrado realizar una conexion HTTP";

        echo "Hola: Soy Chovi Gamez";
        echo "<BR>";
        
        $cadena.="<br>";
        $cadena.="sin necesitad de un navegador";
        $cadena.="<br>";
        $cadena.="Conexion via SHIELD GSM/GPRS SIM900";
        $cadena.="<br>";
        
        echo $cadena;
        
        echo "Saludos cordiales mis estimados colegas de la comunidad no dormimos. Jojojo jo...";
?>
</body>
</html>